/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/accounts`; params?: Router.UnknownInputParams; } | { pathname: `/add-account`; params?: Router.UnknownInputParams; } | { pathname: `/add-category`; params?: Router.UnknownInputParams; } | { pathname: `/add-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/edit-account`; params?: Router.UnknownInputParams; } | { pathname: `/edit-category`; params?: Router.UnknownInputParams; } | { pathname: `/edit-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transactions` | `/transactions`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/accounts`; params?: Router.UnknownOutputParams; } | { pathname: `/add-account`; params?: Router.UnknownOutputParams; } | { pathname: `/add-category`; params?: Router.UnknownOutputParams; } | { pathname: `/add-transaction`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-account`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-category`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-transaction`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/transactions` | `/transactions`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/accounts${`?${string}` | `#${string}` | ''}` | `/add-account${`?${string}` | `#${string}` | ''}` | `/add-category${`?${string}` | `#${string}` | ''}` | `/add-transaction${`?${string}` | `#${string}` | ''}` | `/edit-account${`?${string}` | `#${string}` | ''}` | `/edit-category${`?${string}` | `#${string}` | ''}` | `/edit-transaction${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/transactions${`?${string}` | `#${string}` | ''}` | `/transactions${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/accounts`; params?: Router.UnknownInputParams; } | { pathname: `/add-account`; params?: Router.UnknownInputParams; } | { pathname: `/add-category`; params?: Router.UnknownInputParams; } | { pathname: `/add-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/edit-account`; params?: Router.UnknownInputParams; } | { pathname: `/edit-category`; params?: Router.UnknownInputParams; } | { pathname: `/edit-transaction`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transactions` | `/transactions`; params?: Router.UnknownInputParams; };
    }
  }
}
